# **Day 5 Assignment - NumPy**

q1: Create a 1D array of numbers from 0 to 9

In [ ]:
#solution
import numpy as np
arr = np.arange(0, 10, 1)
print(f"array from 0 to 9 is: {arr}")

array from 0 to 9 is: [0 1 2 3 4 5 6 7 8 9]


q2: Create a 3×3 numpy array of all True’s

In [ ]:
#solution
import numpy as np

arr = np.full((3,3), True, dtype = bool)
print(f"the 3x3 numpy array of all true's is: \n{arr}")

the 3x3 numpy array of all true's is: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


q3: Extract all odd numbers from an array of n numbers

In [ ]:
#solution

n = int(input("enter number of values in array: "))
arr = np.empty(n, dtype = int)
arr2 = []

for i in range(n):
  arr[i] = int(input(f"enter {i}th value: "))
  if(arr[i]%2 != 0):
    arr2.append(arr[i])

print(f"the odd values are : {arr2}")

enter number of values in array: 5
enter 0th value: 1
enter 1th value: 2
enter 2th value: 3
enter 3th value: 4
enter 4th value: 5
the odd values are : [1, 3, 5]


q4: Replace all odd numbers in array with -1

In [ ]:
#solution
import numpy as np
arr = np.arange(0, 11, 1, dtype = int)

for i in range(len(arr)):
  if(arr[i] %2 != 0):
    arr[i] = -1

print(f"after replacing all odd numbers in array with -1, array becomes: {arr}")

after replacing all odd numbers in array with -1, array becomes: [ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


q5: Convert a 1D array to a 2D array with 2 rows


In [ ]:
#solution
import numpy as np

arr1 = np.array([0, 1, 2, 3, 4, 5])
arr1 = arr1.reshape((2,3))

print(f"after reshaping the array in 2D with 2 rows, the array becomes: \n{arr1}")

after reshaping the array in 2D with 2 rows, the array becomes: 
[[0 1 2]
 [3 4 5]]


q6: Get the common items between two arrays

In [ ]:
#solution
import numpy as np
arr1 = np.array([1, 2, 3, 5, 4, 85, 15, 36, 24, 59])
print(f"array 1 is: {arr1}")

arr2 = np.array([2, 5, 3, 21, 52 ,15, 64, 36, 75])
print(f"array 2 is: {arr2}")

print(f"the common elements in array 1 and array 2 are: {np.intersect1d(arr1, arr2)}")

array 1 is: [ 1  2  3  5  4 85 15 36 24 59]
array 2 is: [ 2  5  3 21 52 15 64 36 75]
the common elements in array 1 and array 2 are: [ 2  3  5 15 36]


q7: From array - a remove all items present in array - b

In [ ]:
#solution
import numpy as np
a = np.array([1, 2, 3, 5, 4, 85, 15, 36, 24, 59])
b = np.array([2, 3, 5, 7, 85, 16, 25, 68, 69 ,32])
x = np.array([])

for i in a:
  x= np.where( b == i)

print(x)

(array([], dtype=int64),)


# Download the Iris Data CSV File from link - https://drive.google.com/file/d/1KzIR0hK9F17jhzOT3KH2mmWrCoDWpDpQ/view?usp=sharing

# And Write Program for following Questions:

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Summer Training/Iris.csv')

q8: Find the mean, median, standard deviation of iris's sepallength (1st column)

In [31]:
#solution
df2 = df['SepalLengthCm'].mean()
print(f"mean of SepalLength is: {df2}")

df3 = df['SepalLengthCm'].median()
print(f"median of SepalLength is: {df3}")

df4 = df['SepalLengthCm'].std()
print(f"Standard deviation of SepalLength is: {df4}")

mean of SepalLength is: 5.843333333333334
median of SepalLength is: 5.8
Standard deviation of SepalLength is: 0.828066127977863


q9: Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

Use following Normalization Formula ->

 x normalized = (x – x minimum) / (x maximum – x minimum)

In [14]:
#solution
min = df["SepalLengthCm"].min()
max = df["SepalLengthCm"].max()
l2 = []

for i in df["SepalLengthCm"]:
  val = (i - min) / (max - min)
  l2.append(val)

print("adding a new column to add normalized values.")
df.assign(Sepal_normalized = l2)

adding a new column to add normalized values.


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  Sepal_normalized  
0       Iris-setosa          0.222222  
1       Iris-setosa          0.166667  
2       Iris-setosa          0.111111  
3       Iris-setosa          0.083333  
4       Iris-setosa          0.194444  
..              ...               ...  
145  Iris-virginica          0.666667  
146  Iris-virginica          0.555556  
147  Iris-virginica          0.611111  
148  Iris-virginica          0.527778  
149  Iris-virginica          0.444444  

[150 rows x 7 columns]

q10: Filter the rows of iris data that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [27]:
df3 = df[(df["SepalLengthCm"] < 5.0) & (df['PetalLengthCm'] > 1.5) ]
df3

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
11    12            4.8           3.4            1.6           0.2   
24    25            4.8           3.4            1.9           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
57    58            4.9           2.4            3.3           1.0   
106  107            4.9           2.5            4.5           1.7   

             Species  
11       Iris-setosa  
24       Iris-setosa  
29       Iris-setosa  
30       Iris-setosa  
57   Iris-versicolor  
106   Iris-virginica

q12: Bin the petal length (3rd) column of iris data to form a text array, such that if petal length is:

Less than 3 --> 'small'

3-5 --> 'medium'

->5 --> 'large'


In [20]:
#solution
l2 = []

for i in df["PetalLengthCm"]:
  if(i < 3):
    l2.append("small")
  elif(i < 3.5):
    l2.append("medium")
  else:
    l2.append("large")

print("adding a new column to add text array for small/medium/large values.")
df.assign(PetalLength = l2)

adding a new column to add text array for small/medium/large values.


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species PetalLength  
0       Iris-setosa       small  
1       Iris-setosa       small  
2       Iris-setosa       small  
3       Iris-setosa       small  
4       Iris-setosa       small  
..              ...         ...  
145  Iris-virginica       large  
146  Iris-virginica       large  
147  Iris-virginica       large  
148  Iris-virginica       large  
149  Iris-virginica       large  

[150 rows x 7 columns]

q13: Sort the iris dataset based on sepallength column.

In [24]:
#solution
df2 = df.sort_values("SepalLengthCm")
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
13    14            4.3           3.0            1.1           0.1   
42    43            4.4           3.2            1.3           0.2   
38    39            4.4           3.0            1.3           0.2   
8      9            4.4           2.9            1.4           0.2   
41    42            4.5           2.3            1.3           0.3   
..   ...            ...           ...            ...           ...   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   
117  118            7.7           3.8            6.7           2.2   
135  136            7.7           3.0            6.1           2.3   
131  132            7.9           3.8            6.4           2.0   

            Species  
13      Iris-setosa  
42      Iris-setosa  
38      Iris-setosa  
8       Iris-setosa  
41      Iris-setosa  
..              ...  
122  Iris-virginica  
118  Iris-virginica  
117  Iris-virginica  
135  Iris-virginica  
131  Iris-virginica  

[150 rows x 6 columns]

q14: Find the most frequent value of petal length (3rd column) in iris dataset.

In [55]:
#solution
df5 = df["PetalLengthCm"].mode()
print(f"the most frequent value is: {df5}")

the most frequent value is: 0    1.5
Name: PetalLengthCm, dtype: float64


# Practice Problems

Ques. import NumPy

In [ ]:
import numpy as np
import sys

li_arr = [i for i in range(10)]        #create list of 10 elements
np_arr = np.arange(10)                #create numpy array of 10 elements

In [ ]:
#size of 10 elements in numpy array
print(np_arr.itemsize * np_arr.size)

80


In [ ]:
#size of 10 elements in python list
print(sys.getsizeof(1)*len(li_arr))

280


Ques. make an array using numpy arange

In [ ]:
#np.arange(0, 10)
np.arange(0,10 ,2)

array([0, 2, 4, 6, 8])

Ques. Create a zeroes array using numpy zeroes function

In [ ]:
import numpy as np
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Ques. Print type of NumPy array

In [ ]:
l = [1, 2, 3, '5', 4.5]
b = np.array(a*3)
print(type(b))

<class 'numpy.ndarray'>


Ques. Create a Numpy array from list

In [ ]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [ ]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [ ]:
b = np.ones((2,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

Ques. Use linspace function

In [ ]:
np.linspace(0, 30 ,5 )

array([ 0. ,  7.5, 15. , 22.5, 30. ])

Ques. Creating a ndarray using np.full()

In [ ]:
b = np.full((3, 3), 5, dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

Ques. Show the difference between np.arange() and np.linspace()

In [47]:
 np.arange(3, 7, 2, dtype=int)

array([3, 5])

In [48]:
np.linspace(2.0, 3.0,  num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

Ques. use randint to create a random number

In [38]:
import random
a = random.randint(0, 10)
print(f"a random number from 0 to 10 is: {a}")

a random number from 0 to 10 is: 8


Ques. WAP to replace all even numbers by 2

In [ ]:
import numpy as np
arr = np.arange(0, 11, 1, dtype = int)

for i in range(len(arr)):
  if(arr[i] %2 == 0):
    arr[i] = 2

print(arr)

[2 1 2 3 2 5 2 7 2 9 2]


Ques. using brackets for indexing and selection in numpy array

In [ ]:
#getting value at position 4 using brackets
import numpy as np
arr = np.arange(0, 11, 1, dtype = int)
arr[4]

4

In [ ]:
#getting values from a range selection
arr[:4]

array([0, 1, 2, 3])

In [ ]:
#getting values from specific index positions
arr[[0, 4, 7]]

array([0, 4, 7])

Ques. WAP to find index of arrays where two elements match. eg: take two array as input and match their index values, if same print index.

In [46]:
import math
import numpy as np
arr = np.array([])
arr2 = np.array([])
idx = np.array([])

n = int(input("enter number of values for first list: "))

for i in range(n):
  x = int(input(f"enter {i}th value: "))
  arr = np.append(arr, x)

n1 = int(input("enter number of values for first list: "))

for i in range(n1):
  x1 = int(input(f"enter {i}th value: "))
  arr2 = np.append(arr2, x1)

for i in range(n):
  if(arr[i] == arr2[i]):
    idx = np.append(idx, i)

print(f"the common indices are: {idx}")

enter number of values for first list: 3
enter 0th value: 1
enter 1th value: 2
enter 2th value: 3
enter number of values for first list: 3
enter 0th value: 2
enter 1th value: 2
enter 2th value: 3
the common indices are: [1. 2.]


Ques. Find max, min, argmax, argmin in a numpy array

In [ ]:
import numpy as np
l = np.array([1, 5, 3, 5, 15, 45, 25, 16])

max = np.max(l)
min = np.min(l)

argmax = np.argmax(l)
argmin = np.argmin(l)

print(f"maximum value in array is: {max}")
print(f"index of maximum value in array is: {argmax}")
print(f"minimum value in array is: {min}")
print(f"index of minimum value in array is: {argmin}")

maximum value in array is: 45
index of maximum value in array is: 5
minimum value in array is: 1
index of minimum value in array is: 0


Ques. Create a list and use normalize it.

In [ ]:
import numpy as np
l = np.array([22, 23, 24 ,35, 36, 40, 39, 52, 58, 65])
l2 = []
max = np.max(l)
min = np.min(l)

den = max - min

for i in range(len(l)):
  val = (l[i] - min) / (den)
  l2.append(val)

l2

[0.0,
 0.023255813953488372,
 0.046511627906976744,
 0.3023255813953488,
 0.32558139534883723,
 0.4186046511627907,
 0.3953488372093023,
 0.6976744186046512,
 0.8372093023255814,
 1.0]

# IN CLASS LAB EXERCISES - 01

#### Import NumPy package as np

In [49]:
import numpy as np

####  01.  Create an empty array of 20 0's and replace the 4th object with the number 5

In [53]:
arr = np.zeros(20)
arr[3] = 5
arr

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### 02. Create an array of 20 1's and store it as a variable named array_master. Copy the same array into another variable named array_copy

In [54]:
array_master = np.ones(20)
array_copy = np.copy(array_master)

print(array_copy)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 03.Create an array containing 30 1's and broadcast all the one's to the value 100

In [65]:
arr = np.ones(30)
arr[:] = 100
print(f"after broadcasting all elements to value 100, {arr}")

after broadcasting all elements to value 100, [100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100.]


#### 04. Create an array of integers starting from 21 until 31 and name it as array1

####  ---     Create an array of integers starting from 11 until 21 and name it array2

####  ---    Calculate the difference between array1 and array2

In [60]:
array1 = np.arange(21,32,1)
array2 = np.arange(11, 22, 1)
diff = array1 - array2
print(f"the difference between the two arrays is: {diff}")

the difference between the two arrays is: [10 10 10 10 10 10 10 10 10 10 10]


#### 05. Create an array of all even integers from 2 to 10 and name it a1

#### --   Create an array of all even integers from 22 to 30 and name it a2

####    a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

In [62]:
a1 = np.arange(2, 11, 2)
a2 = np.arange(22, 31, 2)
a3 = np.stack((a1,a2))
print(a3)

[[ 2  4  6  8 10]
 [22 24 26 28 30]]


####  b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [64]:
a4 = np.column_stack((a1,a2))
print(a4)

[[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]


#### 06. Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [73]:
arr = np.arange(0, 30, 1).reshape(5,6)
print(arr)
print(f"element intersecting at 2nd row and 3rd column is: {arr[1][2]}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
element intersecting at 2nd row and 3rd column is: 8


#### 07. Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [99]:
arr = np.eye(10)

for i in range(10):
  for j in range(10):
    if (arr[i][j] == 0):
      arr[i][j] = 21

print(f"after changing values of 0's to 21: \n{arr}")

after changing values of 0's to 21: 
[[ 1. 21. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21.  1. 21. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21.  1. 21. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21.  1. 21. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21.  1. 21. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21.  1. 21. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21.  1. 21. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21.  1. 21. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21.  1. 21.]
 [21. 21. 21. 21. 21. 21. 21. 21. 21.  1.]]


#### Use NumPy to generate a random set of 10 numbers between 0 and 1

#### 08. Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [93]:
import random

arr = np.random.rand(10)
arr2 = np.array([])

for i in arr:
  if ( i>0.2 ):
    arr2 = np.append(arr2, True)
  else:
    arr2 = np.append(arr2, False)

print(arr2)

[1. 0. 1. 1. 1. 1. 1. 0. 1. 1.]


#### 09. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [87]:
import random

arr = np.random.randn(5,2)
print(f"an array matrix of 5x2 random numbers sampled from a standard normal distribution is: \n{arr}")

an array matrix of 5x2 random numbers sampled from a standard normal distribution is: 
[[-0.7834457   0.15418196]
 [-0.71799319  0.04792871]
 [-0.70529795  0.71233153]
 [ 1.19938883  2.07828634]
 [-0.23222985  0.12527288]]


#### 10. Create an array of 30 linearly spaced points between 0 and 100:

In [101]:
arr = np.linspace(0, 100, 30)
print(f"array of 30 linearly spaced elements between 0 and 100 is: \n{arr} ")

array of 30 linearly spaced elements between 0 and 100 is: 
[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ] 


## Numpy Indexing and Selections

#### 11. Using the below given Matrix, generate the output for the below questions.

In [128]:
arr= np.array([[1, 2, 3, 4, 5, 6],
      [2, 11, 8, 6, 9, 7],
      [12, 10, 55, 35, 62, 14],
      [24, 35, 68, 24 ,35, 15],
      [24, 57, 68 ,20 ,43 ,18],
      [12, 10, 55, 35, 62, 14]
     ])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 2, 11,  8,  6,  9,  7],
       [12, 10, 55, 35, 62, 14],
       [24, 35, 68, 24, 35, 15],
       [24, 57, 68, 20, 43, 18],
       [12, 10, 55, 35, 62, 14]])

#### a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

In [129]:
print(f"the last two rows and 3 columns are: {arr[2:][:3]}")

the last two rows and 3 columns are: [[12 10 55 35 62 14]
 [24 35 68 24 35 15]
 [24 57 68 20 43 18]]


#### b) Retrieve the value 55 from the above matrix using index & selection technique

In [130]:
print(f"value at arr[2][2]: {arr[2][2]}")

value at arr[2][2]: 55


#### c) Retrieve the values from the 3rd column in the above matrix

In [131]:
arr[:][3]

array([24, 35, 68, 24, 35, 15])

#### d) Retrieve the values from the 4th row in the above matrix

In [132]:
arr[4][:]

array([24, 57, 68, 20, 43, 18])

#### e) Retrieve values from the 2nd & 4th rows in the above matrix

In [135]:
arr[2:5:2][:]

array([[12, 10, 55, 35, 62, 14],
       [24, 57, 68, 20, 43, 18]])

### Calculate the following values for the given matrix

In [136]:
import numpy as np

arr= np.array([[1, 2, 3, 4, 5, 6],
      [2, 11, 8, 6, 9, 7],
      [12, 10, 55, 35, 62, 14],
      [24, 35, 68, 24 ,35, 15]
     ])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 2, 11,  8,  6,  9,  7],
       [12, 10, 55, 35, 62, 14],
       [24, 35, 68, 24, 35, 15]])

#### a) Calculate sum of all the values in the matrix

In [137]:
sum = np.sum(arr)
sum

453

#### b) Calculate standard deviation of all the values in the matrix

In [138]:
st = np.std(arr)
st

19.236060970652662

#### c) Calculate the variance of all values in the matrix

In [144]:
var = np.var(arr)
print(f"variance is: {var}")

variance is: 370.0260416666667


#### d) Calculate the mean of all values in the matrix

In [140]:
mean = np.mean(arr)
mean

18.875

#### e) Retrieve the largest number from the matrix

In [142]:
max = np.max(arr)
max

68

#### f) Retrieve the smallest number from the matrix

In [143]:
min = np.min(arr)
min

1